"""cloze_deletions

Revision ID: 5e641ae4295c
Revises: ee7b59fbb322
Create Date: 2025-03-22 16:00:50.597762

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e641ae4295c"
down_revision: Union[str, None] = "ee7b59fbb322"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloze_deletion",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("motif_uuid", sa.String(length=36), nullable=False),
        sa.Column("mask_tuples", sqlite.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["motif_uuid"],
            ["motif.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cloze_deletion")
    # ### end Alembic commands ###
