"""cloze_deletions

Revision ID: 5e641ae4295c
Revises: ee7b59fbb322
Create Date: 2025-03-22 16:00:50.597762

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e641ae4295c"
down_revision: Union[str, None] = "ee7b59fbb322"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloze_deletion",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("motif_uuid", sa.String(length=36), nullable=False),
        sa.Column("mask_tuples", sqlite.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["motif_uuid"],
            ["motif.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###

    # sqlite doesn't support adding an fk to an existing table: recreate and copy data
    op.create_table(
        "reprisal_with_cloze_deletion_fk",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("motif_uuid", sa.String(length=36), nullable=False),
        sa.Column("set_uuid", sa.String(length=36), nullable=False),
        sa.Column("cloze_deletion_uuid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["motif_uuid"],
            ["motif.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["cloze_deletion_uuid"],
            ["cloze_deletion.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )

    op.execute(
        """INSERT INTO reprisal_with_cloze_deletion_fk (uuid, motif_uuid, set_uuid, cloze_deletion_uuid, created_at)
        SELECT uuid, motif_uuid, set_uuid, NULL, created_at FROM reprisal;"""
    )
    op.rename_table("reprisal", "reprisal_old")
    op.rename_table("reprisal_with_cloze_deletion_fk", "reprisal")
    op.drop_table("reprisal_old")


def downgrade() -> None:
    op.create_table(
        "reprisal_without_cloze_deletion_fk",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("motif_uuid", sa.String(length=36), nullable=False),
        sa.Column("set_uuid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["motif_uuid"],
            ["motif.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )

    op.execute(
        """INSERT INTO reprisal_without_cloze_deletion_fk (uuid, motif_uuid, set_uuid, created_at)
        SELECT uuid, motif_uuid, set_uuid, created_at FROM reprisal;"""
    )
    op.rename_table("reprisal", "reprisal_with_cloze_deletion_fk")
    op.rename_table("reprisal_without_cloze_deletion_fk", "reprisal")
    op.drop_table("reprisal_with_cloze_deletion_fk")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cloze_deletion")
    # ### end Alembic commands ###
