"""reprisal table

Revision ID: ee7b59fbb322
Revises: 572c84b8233b
Create Date: 2025-03-08 09:16:04.132411

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee7b59fbb322"
down_revision: Union[str, None] = "572c84b8233b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reprisal",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("motif_uuid", sa.String(length=36), nullable=False),
        sa.Column("set_uuid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["motif_uuid"],
            ["motif.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reprisal")
    # ### end Alembic commands ###
